name: complex workflow
on:
  push:

jobs:
  confidential_data:
    runs-on: ubuntu-latest
    steps:
      - name: confidential_data
        run: echo le secret a pour valeur "${{secrets.SUPER_SECRET}}"