name: matrix
on:
  push:
jobs:
  version_python:
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup_python
        with:
          python-version ${{matrix.version}}
        run: echo python --version